### ISSUE TITLE
Unprivileged containers

### ISSUE THREAD

**Issue by arocnies** [claudyus/LXC-Web-Panel#85] opened 2015-06-26 05:15 UTC
Edit: Figured it out, found another issue, see below.

I am unable to create unprivileged containers. All of my containers are owned by root and I can't find an option to specify another user in the UI or configuration files. Based on a commit message from googley's repo stating LWP supports unprivileged containers, I assume the feature in included in this fork. Am I missing something?

**Comment by arocnies** [comment] 2015-06-26 05:21
I'm an idiot.

For anyone else:
Simply create a user with the same credentials as your desired linux user and login to the webui as that user.

**Comment by cronner** [comment] 2015-07-04 18:57
Can't get it to work, did so that root and another user is Unprivileged 
when trying to create a server with ubuntu 15.04 it says "Error! testserver"
tried database user and pam
also tried to root lwp as another user with the same error

**Comment by cronner** [comment] 2015-07-04 19:03
It uses another command:

#$ lxc-create -n server1 -t debian
This template can't be used for unprivileged containers.
You may want to try the "download" template instead.
lxc-create: lxccontainer.c: create_run_template: 1197 container creation template for avs failed
lxc-create: lxc_create.c: main: 274 Error creating container avs

#$ lxc-create -t download -n server1 -- -d debian -r jessie -a amd64
works in console

**Comment by claudyus** [comment] 2015-07-17 13:49
@arocnies I don't really understand in your second message if there is still a problem or if it was fixed. If so please close the issues

I reproduce your problem @cronner and I believe that it is a configuration issue inherith by default /etc/lxc/default.conf .

```
$ lxc-start -n server1 --logfile /tmp/log.txt
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 346 To get more details, run the container in foreground mode.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
(lxc)cmignanti@cmignanti-asus:~/code/LXC-Web-Panel$ cat /tmp/log.txt 
      lxc-start 1437140286.115 ERROR    lxc_start - start.c:lxc_spawn:1000 - failed to create the configured network
      lxc-start 1437140286.150 ERROR    lxc_start - start.c:__lxc_start:1164 - failed to spawn 'server1'
      lxc-start 1437140291.156 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 1437140291.156 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 1437140291.156 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
```
The error "failed to create the configured network" could be due to ``lxc.include`` in your ``~/.config/lxc/default.conf``

Anyway this is not a LXC-Web-Panel issues.

**Closed** 2015-07-19 03:22 UTC
Labels: question, wontfix
